//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsuBeatmapMixer.Backup {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resourceja_bak {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourceja_bak() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OsuBeatmapMixer.Backup.Resourceja_bak", typeof(Resourceja_bak).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   en-US に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択した譜面を削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmationText1 {
            get {
                return ResourceManager.GetString("ConfirmationText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下の場所のフォルダーに保存しますがよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmationText2 {
            get {
                return ResourceManager.GetString("ConfirmationText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行には2つ以上の譜面が必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText1 {
            get {
                return ResourceManager.GetString("ErrorText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストに異なるゲームモードの譜面が存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText2 {
            get {
                return ResourceManager.GetString("ErrorText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストに異なるManiaモードのキーが存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText3 {
            get {
                return ResourceManager.GetString("ErrorText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストに異なるスライダー感度が存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText4 {
            get {
                return ResourceManager.GetString("ErrorText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最低でもアーティスト名とタイトルが必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText5 {
            get {
                return ResourceManager.GetString("ErrorText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mp3ファイルの保存先を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText6 {
            get {
                return ResourceManager.GetString("ErrorText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理が取り消されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText7 {
            get {
                return ResourceManager.GetString("ErrorText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に完了しました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FinishedText1 {
            get {
                return ResourceManager.GetString("FinishedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageConfirmation {
            get {
                return ResourceManager.GetString("MessageConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageFinished {
            get {
                return ResourceManager.GetString("MessageFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   注意 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストに同じ譜面が存在します。本当に追加しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningText1 {
            get {
                return ResourceManager.GetString("WarningText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は既に存在します。上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningText2 {
            get {
                return ResourceManager.GetString("WarningText2", resourceCulture);
            }
        }
    }
}
