//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsuBeatmapMixer.Backup {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resourceen_bak {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resourceen_bak() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OsuBeatmapMixer.Backup.Resourceen_bak", typeof(Resourceen_bak).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ja-JP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete selected beatmap? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmationText1 {
            get {
                return ResourceManager.GetString("ConfirmationText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to save the file in the folder at the following location? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmationText2 {
            get {
                return ResourceManager.GetString("ConfirmationText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At least 2 beatmaps are required for execution. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText1 {
            get {
                return ResourceManager.GetString("ErrorText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Different game modes are mixed in the list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText2 {
            get {
                return ResourceManager.GetString("ErrorText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Different mania mode keys are mixed in the list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText3 {
            get {
                return ResourceManager.GetString("ErrorText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Different slidermultiplier are mixed in the list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText4 {
            get {
                return ResourceManager.GetString("ErrorText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requires at least the artist name and title. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText5 {
            get {
                return ResourceManager.GetString("ErrorText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify the location of the mp3 file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText6 {
            get {
                return ResourceManager.GetString("ErrorText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorText7 {
            get {
                return ResourceManager.GetString("ErrorText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mix Successful! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FinishedText1 {
            get {
                return ResourceManager.GetString("FinishedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageConfirmation {
            get {
                return ResourceManager.GetString("MessageConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageFinished {
            get {
                return ResourceManager.GetString("MessageFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The same beatmap already exists in the list. Are you sure you want to add it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningText1 {
            get {
                return ResourceManager.GetString("WarningText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists. Are you sure you want to overwrite it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningText2 {
            get {
                return ResourceManager.GetString("WarningText2", resourceCulture);
            }
        }
    }
}
